### ISSUE TITLE
[Site | Bug] Unable to switch to the zh-CN language

### ISSUE THREAD

**Issue by LiuYan-xwx** [iNKORE-NET/Documentation#16]
**Describe the bug**
docs.inkore.net 文档网站右上角的语言选项，当我点击简体中文的时候页面并没有任何变化，依旧是英文。

**To Reproduce**
1. 打开 docs 网站
2. 找到右上角的语言切换选项，点击简体中文（中国）

**Expected behavior**
网站切换为中文

**Screenshots**
![image](https://github.com/user-attachments/assets/641f19b9-a224-4eca-8587-69afeb824412)
![image](https://github.com/user-attachments/assets/33d5e02d-74ee-4e2b-9772-4f55f52e5303)

**Desktop (please complete the following information):**
 - OS: Windows10 22H2
 - Browser Microsoft Edge 版本 128.0.2739.79 (正式版本) (64 位)

**Comment by Aris-Offline** [comment]
已知问题，当时做的时候多语言架构没弄好，索性先顶着个测试版摆烂了
@NotYoojun

**Comment by NotYoojun** [comment]
因为现在多语言系统还没搭好，再加上没人写中文文档，所以就...

**Comment by NotYoojun** [comment]
现在修好了，请看
https://docs.inkore.net/zh-cn/blog/2024/09/17/reflection-interest-in-opensource-community/

**Comment by NotYoojun** [comment]
部分文档没有中文翻译，将展示其他语言原版
